[workspace]
members = [
    "crates/types",
    "crates/common",
]

resolver = "2"

[workspace.dependencies]
proptest = "1.9.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"
thiserror = "1.0.69"
types = { path = "crates/types" }
