[package]
name = "wal"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
common = { workspace = true }
types = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
