[package]
name = "buffer"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
storage = { path = "../storage" }
lru = { workspace = true }
hashbrown = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
